# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20171213_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='e-mail verified'),
        ),
    ]
